### ISSUE TITLE
Missing documentation about the Rakefile

### ISSUE THREAD

**Issue by cornuwel** [TwP/bones#46]
Just discovering bones, and I'm having trouble building my gem:
> WARNING:  licenses is empty, but is recommended.  Use a license identifier from
> http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
> WARNING:  description and summary are identical
> WARNING:  open-ended dependency on bones (>= 3.8.4, development) is not recommended
>   if bones is semantically versioned, use:
>     add_development_dependency 'bones', '~> 3.8', '>= 3.8.4'`

So far, I have been unable to find out what parameters were allowed in the Rakefile. 
Adding a 'licenses' is simply ignored.
I don't know where bones gets the description and summary from. 
Adding "depend_on 'bones', '~> 3.8', :development => true" to the Rakefile causes a blocking error:
> Gem::InvalidSpecificationException: duplicate dependency on bones (>= 3.8.4, development), (~> 3.8) > use:
>     add_development_dependency 'bones', '>= 3.8.4', '~> 3.8'

Help a newbie out? If you want to have a look at my gem to tell me what I did wrong: https://github.com/cornuwel/nvidia-smi

**Comment by TwP** [comment]
This  ticket is so very old - apologies for letting it stagnate.

I've been fixing up some bugs in this gems. To find the available options for the `Rakefile` you can use the `bones:options` and `bones:help` rake commands. The first lists all the available options. The second gives a detailed description of the options along with their current values.

```sh
> rake bones:options
  - authors
  - changes
  - colorize
  - description
  - email
  - history_file
  - ignore_file
  - license
  - name
  - readme_file
  - release_name
  - summary
  - url
  - version
```

I've trimmed it down, but you get the idea.

The next release of bones 3.9.0 will fix the bugs you mentioned.
